### ISSUE TITLE
S8x16Shuffle workloads

### ISSUE THREAD

**Issue by ngzhian** [zeux/wasm-simd#2]
Hi Arseny, I'm looking at RIP-relative loads for V8, trying to address https://bugs.chromium.org/p/v8/issues/detail?id=10117. Do you have any particular workloads in mind that uses some S8x16Shuffles?

I could come up with a synthetic microbenchmark (just shuffle with a mask like 4, 5, 6, 7, 0...0) that showed speed up when we have rip-relative loads, and would like to see the performance difference with a bigger workload.

**Comment by zeux** [comment]
Yup, I can easily make a runnable benchmark using the original code I filed in that issue which is a real workload with just a small part of it in the shuffle. Stay tuned...

**Comment by zeux** [comment]
You can run the attached files with
```
v8 --experimental-wasm-simd codecbench-simd.js
```

Here's the benchmark built with all the workarounds to make sure LLVM doesn't generate shuffles that don't pattern match in v8:
[codecbench-simd-optimal.zip](https://github.com/zeux/wasm-simd/files/4484763/codecbench-simd-optimal.zip)

```
filter: oct8 14.08 ms (2.12 GB/sec), oct12 15.35 ms (3.88 GB/sec), quat12 21.79 ms (2.74 GB/sec), exp 4.80 ms (12.43 GB/sec)
```

Here's the same code where I removed a workaround in the `oct12` function and replaced a couple and/or sequences with a shuffle that should map to pblendw but doesn't due to LLVM optimizations (if I recall correctly):
[codecbench-simd-slow.zip](https://github.com/zeux/wasm-simd/files/4484777/codecbench-simd-slow.zip)

```
filter: oct8 14.08 ms (2.12 GB/sec), oct12 41.39 ms (1.44 GB/sec), quat12 21.96 ms (2.71 GB/sec), exp 4.78 ms (12.47 GB/sec)
```

As you can see the perf cliff here is really significant; I'd expect that with RIP-relative pshufb the impact is much less significant.

**Comment by zeux** [comment]
Looks like this can be closed now :) Thanks for implementing the optimization!

**Comment by ngzhian** [comment]
@zeux do you mind rebuilding these samples (or giving me instructions to build them) with the latest opcode changes? I would like this to evaluate shuffle performance for ia32.

**Comment by zeux** [comment]
Here you go
[codecbench.zip](https://github.com/zeux/wasm-simd/files/4731648/codecbench.zip)

**Comment by omnisip** [comment]
> Here you go
> [codecbench.zip](https://github.com/zeux/wasm-simd/files/4731648/codecbench.zip)

Hey @zeux,

I'm reviewing this as part of the proposal to add a PC-relative constant pool for x86 and x64.  Can you help me understand the difference between opt and slow a bit better?  Also, would it be possible to provide a new build of each that takes advantage of v128.const?

On some level it looks like both will take immediate advantage of improvements in the i32->f32 conversion operations, but I'm also curious to see how much it will benefit from improved shuffle lowerings and elimination of stuff like this:

```webassembly
 001266: fd 17 02                   |     i8x16.replace_lane 2
 001269: 41 00                      |     i32.const 0
 00126b: fd 17 03                   |     i8x16.replace_lane 3
 00126e: 41 00                      |     i32.const 0
 001270: fd 17 06                   |     i8x16.replace_lane 6
 001273: 41 00                      |     i32.const 0
 001275: fd 17 07                   |     i8x16.replace_lane 7
 001278: 41 00                      |     i32.const 0
 00127a: fd 17 0a                   |     i8x16.replace_lane 10
 00127d: 41 00                      |     i32.const 0
 00127f: fd 17 0b                   |     i8x16.replace_lane 11
 001282: 41 00                      |     i32.const 0
 001284: fd 17 0e                   |     i8x16.replace_lane 14
 001287: 41 00                      |     i32.const 0
 001289: fd 17 0f                   |     i8x16.replace_lane 15
 00128c: fd 4e                      |     v128.and
```

**Comment by zeux** [comment]
My recollection is that "opt" was the version where LLVM shuffle merging was blocked and all shuffles in the time-critical loop would have optimal lowering to SSE instructions, whereas "slow" was the version where LLVM optimizations introduced shuffles that couldn't be lowered efficiently; when v8 used very suboptimal lowering that modified stack pointer, that resulted in a catastrophic performance.

Are you seeing v128.const used in the inner loop? I didn't think it is but I could be wrong about that. I'm not sure what the support status is for v128.const in Emscripten.
